var readline = require("readline-sync")
var enter = 0
console.log("Please accept our terms and conditions:\nPress the E.N.T.E.R. Key to continue (get it)")
readline.question()
enter++
console.log("Will, John, and Luke (©) are not responsible for any harm caused to the END USER or the COMPUTER, such as: Thinking, Feeling, Breathing, Bleeding, Broken Bones, Severed Limbs, Headaches, or Deaths (or the meme that is living!). Please read and accept the following terms and conditions:\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae tortor condimentum lacinia quis vel eros donec ac odio. Morbi tristique senectus et netus et malesuada. Leo vel fringilla est ullamcorper eget nulla facilisi. Ipsum consequat nisl vel pretium lectus. Mi bibendum neque egestas congue quisque egestas diam in. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. Et magnis dis parturient montes nascetur. Euismod in pellentesque massa placerat duis ultricies lacus sed. Tortor pretium viverra suspendisse potenti nullam. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Sed risus pretium quam vulputate dignissim suspendisse in. Iaculis urna id volutpat lacus. Lorem donec massa sapien faucibus et molestie ac. Mattis enim ut tellus elementum sagittis vitae et leo duis. Sed nisi lacus sed viverra tellus in hac. Posuere lorem ipsum dolor sit. Auctor neque vitae tempus quam pellentesque. A diam sollicitudin tempor id eu nisl. Mollis aliquam ut porttitor leo a diam sollicitudin tempor.")
readline.question()
enter++
console.log("Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Pellentesque diam volutpat commodo sed egestas. Senectus et netus et malesuada. Lobortis feugiat vivamus at augue. Sit amet mattis vulputate enim. Elementum nibh tellus molestie nunc non. Mattis aliquam faucibus purus in massa tempor nec feugiat nisl. Molestie at elementum eu facilisis sed. Nulla porttitor massa id neque. Amet purus gravida quis blandit turpis cursus in. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Iaculis at erat pellentesque adipiscing commodo. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Eros donec ac odio tempor orci dapibus ultrices in. Vulputate enim nulla aliquet porttitor. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Quisque non tellus orci ac auctor augue mauris. Sagittis nisl rhoncus mattis rhoncus urna neque. Elementum sagittis vitae et leo duis ut diam.")
readline.question()
enter++
console.log("Porttitor lacus luctus accumsan tortor posuere. Bibendum est ultricies integer quis auctor. Sit amet est placerat in egestas erat imperdiet sed. A arcu cursus vitae congue mauris. Fames ac turpis egestas integer eget aliquet nibh. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Ultrices mi tempus imperdiet nulla malesuada. Tincidunt eget nullam non nisi est sit amet facilisis. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Cursus risus at ultrices mi tempus imperdiet nulla. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Id volutpat lacus laoreet non curabitur gravida arcu. Ligula ullamcorper malesuada proin libero nunc. Dui id ornare arcu odio ut sem nulla. Turpis egestas pretium aenean pharetra magna ac placerat. At augue eget arcu dictum. In arcu cursus euismod quis viverra nibh cras pulvinar. Nec feugiat nisl pretium fusce id velit ut tortor pretium.")
readline.question()
enter++
console.log("Velit sed ullamcorper morbi tincidunt ornare massa. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Urna porttitor rhoncus dolor purus non enim praesent. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Viverra nam libero justo laoreet sit amet cursus. Quis vel eros donec ac odio tempor orci dapibus ultrices. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada. Ornare suspendisse sed nisi lacus sed viverra tellus in. Lobortis elementum nibh tellus molestie nunc non blandit. Diam sit amet nisl suscipit. At augue eget arcu dictum varius duis at consectetur. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit.")
readline.question()
enter++
console.log("In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Non diam phasellus vestibulum lorem sed risus ultricies tristique. Urna molestie at elementum eu facilisis sed odio morbi quis. Lacus sed turpis tincidunt id. A arcu cursus vitae congue mauris rhoncus aenean. Convallis tellus id interdum velit laoreet id donec ultrices tincidunt. Sed vulputate odio ut enim blandit volutpat. Lorem donec massa sapien faucibus et molestie ac feugiat. Lectus quam id leo in vitae turpis massa sed. Et netus et malesuada fames ac turpis egestas. Tortor at risus viverra adipiscing at in tellus.")
readline.question()
enter++
console.log("In cursus turpis massa tincidunt dui ut ornare lectus. Accumsan in nisl nisi scelerisque eu. Eget nunc scelerisque viverra mauris. Rutrum quisque non tellus orci. Enim sed faucibus turpis in. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. At quis risus sed vulputate odio. Quam viverra orci sagittis eu volutpat odio. Neque viverra justo nec ultrices dui sapien eget mi proin. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Tempus quam pellentesque nec nam aliquam sem et. Quis commodo odio aenean sed adipiscing diam. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Aliquam vestibulum morbi blandit cursus risus at ultrices. Sit amet consectetur adipiscing elit ut aliquam purus. Commodo nulla facilisi nullam vehicula ipsum a arcu. Nisl pretium fusce id velit ut. Pharetra vel turpis nunc eget.")
readline.question()
enter++
console.log("Amet aliquam id diam maecenas ultricies mi eget mauris. Vitae congue eu consequat ac felis donec et odio. Tellus in hac habitasse platea dictumst. Sem nulla pharetra diam sit amet nisl. Vel risus commodo viverra maecenas. Ante metus dictum at tempor commodo ullamcorper. Sit amet aliquam id diam. Felis imperdiet proin fermentum leo vel orci porta non pulvinar. Eros in cursus turpis massa tincidunt dui ut ornare. Volutpat blandit aliquam etiam erat velit scelerisque in. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Odio morbi quis commodo odio. Sapien eget mi proin sed libero. Imperdiet nulla malesuada pellentesque elit eget.")
readline.question()
enter++
console.log("Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Elementum sagittis vitae et leo. Maecenas accumsan lacus vel facilisis. Placerat in egestas erat imperdiet sed. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Turpis massa tincidunt dui ut ornare lectus sit. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Leo integer malesuada nunc vel risus. Bibendum est ultricies integer quis auctor. Sed cras ornare arcu dui. Semper eget duis at tellus. Eu volutpat odio facilisis mauris. Dapibus ultrices in iaculis nunc sed augue lacus viverra. Purus semper eget duis at tellus.")
readline.question()
enter++
console.log("Donec massa sapien faucibus et molestie ac. Quam id leo in vitae turpis massa. Adipiscing vitae proin sagittis nisl rhoncus mattis. Lacus luctus accumsan tortor posuere ac. Dui vivamus arcu felis bibendum. Euismod lacinia at quis risus sed vulputate odio ut enim. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Viverra nam libero justo laoreet sit amet cursus sit amet. Amet volutpat consequat mauris nunc congue nisi vitae. Ornare arcu odio ut sem nulla pharetra. Lectus sit amet est placerat in egestas erat imperdiet. Vitae nunc sed velit dignissim sodales ut eu. Tristique senectus et netus et malesuada fames ac turpis egestas. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Nunc mattis enim ut tellus.")
readline.question()
enter++
console.log("Quam elementum pulvinar etiam non quam lacus suspendisse. Pulvinar neque laoreet suspendisse interdum consectetur libero. In arcu cursus euismod quis. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Adipiscing elit duis tristique sollicitudin nibh sit amet. Nulla posuere sollicitudin aliquam ultrices sagittis. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Euismod in pellentesque massa placerat duis ultricies. Amet nulla facilisi morbi tempus iaculis. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nibh sit amet commodo nulla. Volutpat diam ut venenatis tellus in metus. Accumsan in nisl nisi scelerisque.")
readline.question()
enter++
console.log("Consectetur a erat nam at lectus. Nisl vel pretium lectus quam id leo in vitae. Turpis in eu mi bibendum neque egestas congue quisque egestas. Sit amet consectetur adipiscing elit duis. Non tellus orci ac auctor. Accumsan tortor posuere ac ut consequat semper. Nunc sed velit dignissim sodales ut eu sem. Odio morbi quis commodo odio aenean sed. Viverra aliquet eget sit amet. Faucibus purus in massa tempor nec feugiat. Faucibus pulvinar elementum integer enim neque volutpat ac. Lectus quam id leo in vitae. A condimentum vitae sapien pellentesque habitant morbi tristique senectus.")
readline.question()
enter++
console.log("Euismod quis viverra nibh cras pulvinar mattis. Mauris in aliquam sem fringilla ut. Arcu cursus euismod quis viverra. Quam elementum pulvinar etiam non. Turpis tincidunt id aliquet risus feugiat. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Non quam lacus suspendisse faucibus. In fermentum et sollicitudin ac orci. Facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas diam in arcu cursus euismod quis viverra nibh cras. Convallis posuere morbi leo urna. Nulla facilisi nullam vehicula ipsum a arcu cursus. Vestibulum mattis ullamcorper velit sed. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Et odio pellentesque diam volutpat commodo sed egestas egestas. A arcu cursus vitae congue mauris rhoncus aenean. Mi bibendum neque egestas congue quisque egestas diam. Aliquam ut porttitor leo a diam sollicitudin. Nibh ipsum consequat nisl vel pretium lectus quam. Euismod lacinia at quis risus sed.")
readline.question()
enter++
console.log("Sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis. Arcu ac tortor dignissim convallis aenean et. In metus vulputate eu scelerisque felis. Tellus pellentesque eu tincidunt tortor aliquam nulla. In hac habitasse platea dictumst vestibulum rhoncus. Et tortor at risus viverra adipiscing at in. Eget nullam non nisi est sit. Adipiscing bibendum est ultricies integer quis auctor elit sed. Augue mauris augue neque gravida in fermentum. Tellus elementum sagittis vitae et. Eu sem integer vitae justo eget. Viverra mauris in aliquam sem fringilla ut. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Etiam dignissim diam quis enim. Non tellus orci ac auctor augue. Eget lorem dolor sed viverra ipsum nunc.")
readline.question()
enter++
console.log(enter)

